### PR TITLE
New features

### PR DESCRIPTION
**Pull request by PaulJBis**
Here are the new features I mentioned. Specifically, they are:

-in "Ramp", added checkbox to use the parameters of process 2010.
-In "Ramp Multiple", added checkbox to use the parameters of process 2010.
-in "Deflicker", added checkbox to use the EV parameters of process 2010.
-in "Deflicker", added checkbox to save the EV deflickering data to an external JSON file.
-Added a new "Undo" feature. Before each action, it will call this function to save the current metadata in an external JSON file ("undoData.json"). Afterwards, you can pick in a dropdown menu the action you want to go back to.

Some notes:

-My functions and variable names are in spanish. Hope you don't mind :-), but I can change them if you want to.
-There are specific places where I need to get a list of all pictures in a given folder, but exclude all non-picture files. Right now, the code that does this only detects Canon CR2 files (extension "cr2"). It would be good to find out the extensions used by other cameras (Nikon, etc.), to add them to the code.

If you have any other questions, feel free to ask.

### CODE REVIEW

**Comment by davidmilligan** [comment]
thanks, it looks good for the most part there are just a couple of things:

I'd prefer if your variable names were English, I don't really mind it, but it's just kind of strange to have half the source code in Spanish.

It seems you 'based' your changes on the wrong changeset, as the diff shows you deleting a couple of things I recently added. You were probably working off of an older copy of the script, but added the changes to the head in git. You either need to find the commit that corresponds to the version of the script that you modified and base your changes off of that (git will automatically handle the fact that it's not the most recent, when I merge your pull request). Or you can simply get the most recent version of the script and base your changes off of that (add back the things that are getting deleted). See the diff for more info (look at the big red sections).

**Comment by PaulJBis** [comment]
Okay, noted. I've been quite busy these last few days (and this coming week too), so I don't know when I'll be able to pick up again, but will do as you mention.

**Comment by davidmilligan** [comment]
that's fine, the main thing would be translating the variable names, if you can do that, I'll fix everything else

**Comment by PaulJBis** [comment]
Okay. Just translated the variable names.

**Pull request merged**
